import type { Submission, BidEvent } from './types';

const now = Date.now();
const ago = (mins: number) => new Date(now - mins * 60_000).toISOString();

/**
 * Seed data. The board is never empty — an empty corkboard is a bad screenshot,
 * and the first real bidder should land next to plausible neighbours.
 */
export const MOCK_SUBMISSIONS: Submission[] = [
  {
    id: 'sub_01',
    title: 'Vantage',
    tagline: 'Revenue intelligence that actually closes the loop.',
    url: 'https://example.com/vantage',
    logoUrl: null,
    category: 'fintech',
    currentBid: 2400,
    bidderName: 'M. Kessler',
    claimedAt: ago(14),
    status: 'active',
  },
  {
    id: 'sub_02',
    title: 'Nullpoint',
    tagline: 'Ship migrations without the 3am rollback.',
    url: 'https://example.com/nullpoint',
    logoUrl: null,
    category: 'devtools',
    currentBid: 1310,
    bidderName: 'anon',
    claimedAt: ago(38),
    status: 'active',
  },
  {
    id: 'sub_03',
    title: 'Marrow',
    tagline: 'The agent runtime for teams that hate agents.',
    url: 'https://example.com/marrow',
    logoUrl: null,
    category: 'ai',
    currentBid: 880,
    bidderName: 'D. Okonkwo',
    claimedAt: ago(51),
    status: 'active',
  },
  {
    id: 'sub_04',
    title: 'Pallet',
    tagline: 'Freight ops, unbundled.',
    url: 'https://example.com/pallet',
    logoUrl: null,
    category: 'other',
    currentBid: 605,
    bidderName: 'gray_hat',
    claimedAt: ago(72),
    status: 'active',
  },
  {
    id: 'sub_05',
    title: 'Hush',
    tagline: 'Encrypted notes with nothing to subpoena.',
    url: 'https://example.com/hush',
    logoUrl: null,
    category: 'consumer',
    currentBid: 420,
    bidderName: 'R. Vance',
    claimedAt: ago(96),
    status: 'active',
  },
  {
    id: 'sub_06',
    title: 'Ledgerline',
    tagline: 'Onchain settlement without the onchain part.',
    url: 'https://example.com/ledgerline',
    logoUrl: null,
    category: 'crypto',
    currentBid: 275,
    bidderName: '0xsable',
    claimedAt: ago(120),
    status: 'active',
  },
  {
    id: 'sub_07',
    title: 'Coldbrew Studio',
    tagline: 'Brand systems for companies with one shot.',
    url: 'https://example.com/coldbrew',
    logoUrl: null,
    category: 'agency',
    currentBid: 190,
    bidderName: 'studio',
    claimedAt: ago(150),
    status: 'active',
  },
  {
    id: 'sub_08',
    title: 'Tinderbox',
    tagline: 'Incident response that reads the room.',
    url: 'https://example.com/tinderbox',
    logoUrl: null,
    category: 'devtools',
    currentBid: 120,
    bidderName: 'oncall',
    claimedAt: ago(180),
    status: 'active',
  },
  {
    id: 'sub_09',
    title: 'Fathom Labs',
    tagline: 'Deep research, shallow pricing.',
    url: 'https://example.com/fathom',
    logoUrl: null,
    category: 'ai',
    currentBid: 75,
    bidderName: 'anon',
    claimedAt: ago(210),
    status: 'active',
  },
  {
    id: 'sub_10',
    title: 'Kettle',
    tagline: 'Group buying for restaurant supply.',
    url: 'https://example.com/kettle',
    logoUrl: null,
    category: 'consumer',
    currentBid: 48,
    bidderName: 'J. Ferrer',
    claimedAt: ago(240),
    status: 'active',
  },
  {
    id: 'sub_11',
    title: 'Sable & Co',
    tagline: 'Fractional CFO, full-time paranoia.',
    url: 'https://example.com/sable',
    logoUrl: null,
    category: 'fintech',
    currentBid: 31,
    bidderName: 'sable',
    claimedAt: ago(280),
    status: 'active',
  },
  {
    id: 'sub_12',
    title: 'Loomis',
    tagline: 'Physical mail as an API.',
    url: 'https://example.com/loomis',
    logoUrl: null,
    category: 'other',
    currentBid: 22,
    bidderName: 'anon',
    claimedAt: ago(320),
    status: 'active',
  },
  {
    id: 'sub_13',
    title: 'Prowl',
    tagline: 'Competitor tracking, hourly.',
    url: 'https://example.com/prowl',
    logoUrl: null,
    category: 'ai',
    currentBid: 14,
    bidderName: 'nightshift',
    claimedAt: ago(360),
    status: 'active',
  },
  {
    id: 'sub_14',
    title: 'Grain',
    tagline: 'Film-look LUTs for people who shoot digital.',
    url: 'https://example.com/grain',
    logoUrl: null,
    category: 'consumer',
    currentBid: 9,
    bidderName: 'anon',
    claimedAt: ago(400),
    status: 'active',
  },
  {
    id: 'sub_15',
    title: 'Deadbolt',
    tagline: 'Secrets rotation nobody has to remember.',
    url: 'https://example.com/deadbolt',
    logoUrl: null,
    category: 'devtools',
    currentBid: 5,
    bidderName: 'anon',
    claimedAt: ago(440),
    status: 'active',
  },
];
